npmPublishRegistry: 'https://registry.npmjs.org'

packageExtensions:
  '@jest/reporters@*':
    dependencies:
      '@types/istanbul-lib-coverage': 2.0.3
  '@resolver-engine/imports-fs@*':
    dependencies:
      '@resolver-engine/core': 0.3.3
  jest-cli@*:
    dependencies:
      '@types/yargs': 15.0.7
  jest-resolve@25.5.1:
    dependencies:
      jest-haste-map: 26.3.0
  pino@*:
    dependencies:
      pino-pretty: 4.2.1
  '@statechannels/wasm-utils@*':
    dependencies:
      '@statechannels/nitro-protocol': 0.3.6
  babel-plugin-const-enum@*:
    dependencies:
      '@babel/generator': 7.11.6
  '@d8660091/react-popper@*':
    dependencies:
      'react': 16.12.0
  '@rimble/icons@*':
    dependencies:
      styled-system: 5.1.5

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-berry.js
