yarnPath: '.yarn/releases/yarn-berry.js'
npmPublishRegistry: 'https://registry.npmjs.org'
packageExtensions:
  jest-resolve@25.5.1:
    dependencies:
      jest-haste-map: '26.3.0'
  jest-cli@*:
    dependencies:
      '@types/yargs': '15.0.7'
  '@jest/reporters@*':
    dependencies:
      '@types/istanbul-lib-coverage': '2.0.3'
  '@resolver-engine/imports-fs@*':
    dependencies:
      '@resolver-engine/core': '0.3.3'
