nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

packageExtensions:
  "@d8660091/react-popper@*":
    dependencies:
      react: 16.12.0
  "@docusaurus/core@*":
    dependencies:
      "@docusaurus/preset-classic": 2.0.0-alpha.64
  "@jest/reporters@*":
    dependencies:
      "@types/istanbul-lib-coverage": 2.0.3
  "@resolver-engine/imports-fs@*":
    dependencies:
      "@resolver-engine/core": 0.3.3
  "@rimble/icons@*":
    dependencies:
      styled-system: 5.1.5
  "@statechannels/wasm-utils@*":
    dependencies:
      "@statechannels/nitro-protocol": 0.3.6
  "@storybook/core@*":
    dependencies:
      ts-loader: 7.0.5
  babel-plugin-const-enum@*:
    dependencies:
      "@babel/generator": 7.11.6
  ganache-cli@6.11.0:
    dependencies:
      bn.js: 5.1.3
  jest-cli@*:
    dependencies:
      "@types/yargs": 15.0.7
  jest-resolve@25.5.1:
    dependencies:
      jest-haste-map: 26.3.0
  pino@*:
    dependencies:
      pino-pretty: 4.2.1
  react-loadable-ssr-addon@*:
    dependencies:
      "@babel/runtime": 7.11.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
